version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: security-platform
    volumes:
      - ./db/create.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  python_service:
    build:
      context: ./compliance
    container_name: complaince_service
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/compliance
    depends_on:
      - postgres
    ports:
      - "8000:4000"